add fog-painter
owlbear-rodeo/extensions pull request #76
Opened 2024-09-26 22:08 UTC by davidsev

Make sure that your submission has the following:

- [X] A link to the raw github markdown file with a YAML front matter definition containing:
  - [X] The title of your extension
  - [X] A description of your extension
  - [X] The author
  - [X] A hero image
  - [X] An icon
  - [X] Tags (these will help with your extension's discoverability)
  - [X] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [X] You have done your changes in a separate branch.

- [X] You have a descriptive commit message with a short title (first line).

- [X] You have only one commit (if not, squash them into one commit).

- [X] Your pull request MUST target the `main` branch on this repository.

- [X] Your pull request puts your extensions details as the last entry in the extensions.json file

2024-10-28 01:29 UTC, nthouliss requested changes
The only change I'd request for the tool is to allow unselect on the fog brush tool when selecting the icon again (so if it's currently selected, clicking again removes the brush size option like how the fog style tool works). 

Just as a general piece of feedback the documentation makes it seem like using the tool will automatically reveal the fog but this only happens when fog cutting is enabled. This is fine (and probably preferred) but it might be good to clarify this in the docs.

2024-11-02 22:53 UTC, davidsev commented
Thanks for the feedback, those issues have now been resolved.

2024-11-14 05:18 UTC, nthouliss commented
Thanks! The only thing is now the fog brush tool can't be toggled on again 😅 

Reproduction goes:

1. Select fog paint brush (the brush size bar is now open)
2. Select fog paint brush again (the brush size bar is now closed)
3. Select paint brush a third time (the bar doesn't open)

Sorry, it's a bit of a picky one!

2025-10-01 21:20 UTC, davidsev commented
Hi,

Sorry for abadoning this, following some feedback on discord I ended up doing a major rewrite and then running out of time.  I'll make a new PR if I ever get around to polishing it up for release.

2025-10-01 21:20 UTC, closed without merging